### ISSUE TITLE
search the exact restaurant by coordinates

### ISSUE THREAD

**Issue by yuzhou93** [Yelp/yelp-python#54]
I want to search for the restaurant with the exact coordinates of that restaurant. Because I have data from yelp-academic-dataset. However, I can only get a list. I have tried to set "sort" : 1, 'radius_filter': 0; Then sometimes it returns nothing. I noticed that there is a input named "accuracy", however I can find the explanation for how to set this, basically I want 100% accuracy. Is there any solution?

**Comment by mittonk** [comment]
* https://www.yelp.com/developers/documentation/v2/search_api

also isn't very helpful.  I'll dig around, see what I can find --- but I have a hunch `accuracy` is a measure how many digits you have in your lat-lngs, rather than something like "100 % accuracy".

What's one query that returns nothing?  I have a feeling the solution to that will be unrelated to the `accuracy` field, might as well debug that a little.

**Comment by yuzhou93** [comment]
Thanks for the reply. I think maybe it's that I set "radius-filter" as a very small number like 10 or even 1. And my lat,lng is not that accurate. However the lat,lng are exactly obtained from yelp-competition-dataset. Anyway, thanks for your time, at least now I know what "accuracy" means.

**Comment by mittonk** [comment]
That makes sense.  

The smallest `radius_filter` I ever use is about 500 (meters) --- a value like 1 is very fragile with regards to data updates between when the dataset was generated and now, or things like that.

**Comment by yuzhou93** [comment]
Thanks, so is there any way to find the closest restaurant for the given coordinates?
